const assert=require('node:assert/strict');
const {evaluate,curve,calculate}=require('./dist/engine.js');
require('./dist/data.js');const data=globalThis.ELIN_DATA;
require('./dist/traits.js');
assert.equal(globalThis.ELIN_TRAITS.ActArrow.rapid,true);
assert.equal(globalThis.ELIN_TRAITS.ActMissile.rapid,true);
assert.equal(globalThis.ELIN_TRAITS.Spell.rapid,false);
assert.equal(globalThis.ELIN_TRAITS.ActSword.rapid,null);
assert.equal(calculate({spell:'50200',level:10,attribute:30,enhance:100,anti:200},data).power,260);
assert.equal(calculate({spell:'6901',level:10,attribute:30,enhance:100,anti:200},data).power,130);
assert.equal(evaluate('1+p/100+e/10',150,15),4);
assert.equal(evaluate('-1-p/100',50,0),-1);
assert.equal(evaluate('',10,10),0);
assert.equal(evaluate('2+3*4',0,0),14);
assert.equal(curve(400).value,400);assert.equal(curve(401).value,400);assert.equal(curve(600).value,537);
let r=calculate({spell:'50500',level:10,attribute:30,enhance:0,anti:0},data);
assert.equal(r.power,130);assert.equal(r.dice.text,'2d18+5');
assert.equal(r.dice.min,'7');assert.equal(r.dice.max,'41');
r=calculate({spell:'8400',level:10,attribute:30,enhance:0,anti:0},data);
assert.equal(r.dice.text,'2d9+4');
assert.equal(r.dice.min,'6');assert.equal(r.dice.max,'22');
const fixed=calculate({spell:'8406',level:10,attribute:30,enhance:0,anti:0},data);
assert.equal(fixed.dice.min,'100000000');assert.equal(fixed.dice.max,'100000000');
assert.equal(calculate({spell:'8500',level:10,attribute:30,enhance:0,anti:0},data).dice.min,undefined);
assert.equal(calculate({spell:'8400',level:10,attribute:30,enhance:0,anti:200},data).power,1);
assert.throws(()=>evaluate('alert(1)',0,0));
assert.throws(()=>calculate({spell:'8400',level:NaN,attribute:30,enhance:0,anti:0},data));
for(const row of data.calc)for(const key of ['num','sides','bonus'])evaluate(row[key],1234,57);
console.log('Passed: arithmetic, truncation, curve thresholds, spell lookup, healing, anti-magic, invalid inputs, all source formulas.');
const effects=(spell,level=10,enhance=0,anti=0)=>calculate({spell,level,enhance,anti,attribute:30},data).statusEffects;
assert.equal(effects('8710')[0].value,-37);
assert.equal(effects('8510')[0].value,37);
assert.equal(effects('6902')[0].value,122);
assert.deepEqual(effects('8504').map(e=>e.value),[9,9]);
assert.deepEqual(effects('8503').map(e=>e.value),[9,9,6]);
assert.equal(effects('8502')[0].value,23);
assert.deepEqual(effects('8704').map(e=>e.value),[-6,-6,-6]);
assert.equal(effects('8706')[0].value,-93);
assert.equal(effects('8702')[0].text,'半減（50%）');
assert.equal(effects('8710',10,100)[0].value,-44);
assert.equal(effects('8710',10,0,200)[0].value,-21);
assert.deepEqual(effects('50500'),[]);
for(const row of data.elements.filter(r=>r.category==='ability'))effects(row.id);
console.log('Passed: status amounts, signed truncation, speed overrides, enhancement, anti-magic and every ability.');
const songInput={spell:'6752',level:10,attribute:30,enhance:30,anti:999,music:50,diva:2};
assert.equal(calculate(songInput,data).power,299);
assert.equal(calculate({...songInput,diva:0},data).power,214);
assert.equal(calculate({...songInput,anti:0},data).power,299);
assert.equal(calculate({spell:'50800',level:10,attribute:30,enhance:0,anti:0,charisma:80},data).statusEffects[0].value,15);
console.log('Passed: song performance/diva multipliers and charisma-based resistance.');

